name: Automated Unit Testing
on: 
  pull_request:
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2 # Updated to the latest stable version

      - name: Set up NodeJS
        uses: actions/setup-node@v3 # Updated to the latest stable version
        with:
          node-version: 16
          cache: 'npm' # Enable caching for npm dependencies

      - name: Install all dependencies
        run: npm install

      - name: Run Tests
        run: npm run test-unit -- --passWithNoTests

